#FROM mcr.microsoft.com/dotnet/sdk:8.0
FROM mcr.microsoft.com/windowsservercore:latest

#COPY . /home/src
#WORKDIR /home/src
# RUN dotnet build -c Release
#RUN dotnet publish -c Release -o out

#COPY READ-ME.txt /home/app
#COPY ./out /home/app
#WORKDIR /home/app

ENTRYPOINT ["powershell", ""]