//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuvoControl.Server.WebServer.ConfigurationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Graphic", Namespace="http://schemas.datacontract.org/2004/07/NuvoControl.Common.Configuration")]
    [System.SerializableAttribute()]
    public partial class Graphic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NuvoControl.Server.WebServer.ConfigurationServiceReference.Building _buildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NuvoControl.Server.WebServer.ConfigurationServiceReference.Source[] _sourcesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Building _building {
            get {
                return this._buildingField;
            }
            set {
                if ((object.ReferenceEquals(this._buildingField, value) != true)) {
                    this._buildingField = value;
                    this.RaisePropertyChanged("_building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Source[] _sources {
            get {
                return this._sourcesField;
            }
            set {
                if ((object.ReferenceEquals(this._sourcesField, value) != true)) {
                    this._sourcesField = value;
                    this.RaisePropertyChanged("_sources");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Building", Namespace="http://schemas.datacontract.org/2004/07/NuvoControl.Common.Configuration")]
    [System.SerializableAttribute()]
    public partial class Building : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NuvoControl.Server.WebServer.ConfigurationServiceReference.Floor[] _floorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NuvoControl.Server.WebServer.ConfigurationServiceReference.Address _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _picturePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _pictureTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Floor[] _floors {
            get {
                return this._floorsField;
            }
            set {
                if ((object.ReferenceEquals(this._floorsField, value) != true)) {
                    this._floorsField = value;
                    this.RaisePropertyChanged("_floors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Address _id {
            get {
                return this._idField;
            }
            set {
                if ((object.ReferenceEquals(this._idField, value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _picturePath {
            get {
                return this._picturePathField;
            }
            set {
                if ((object.ReferenceEquals(this._picturePathField, value) != true)) {
                    this._picturePathField = value;
                    this.RaisePropertyChanged("_picturePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _pictureType {
            get {
                return this._pictureTypeField;
            }
            set {
                if ((object.ReferenceEquals(this._pictureTypeField, value) != true)) {
                    this._pictureTypeField = value;
                    this.RaisePropertyChanged("_pictureType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Source", Namespace="http://schemas.datacontract.org/2004/07/NuvoControl.Common.Configuration")]
    [System.SerializableAttribute()]
    public partial class Source : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NuvoControl.Server.WebServer.ConfigurationServiceReference.Address _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _picturePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _pictureTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Address _id {
            get {
                return this._idField;
            }
            set {
                if ((object.ReferenceEquals(this._idField, value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _picturePath {
            get {
                return this._picturePathField;
            }
            set {
                if ((object.ReferenceEquals(this._picturePathField, value) != true)) {
                    this._picturePathField = value;
                    this.RaisePropertyChanged("_picturePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _pictureType {
            get {
                return this._pictureTypeField;
            }
            set {
                if ((object.ReferenceEquals(this._pictureTypeField, value) != true)) {
                    this._pictureTypeField = value;
                    this.RaisePropertyChanged("_pictureType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/NuvoControl.Common.Configuration")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _deviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _objectIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _deviceId {
            get {
                return this._deviceIdField;
            }
            set {
                if ((this._deviceIdField.Equals(value) != true)) {
                    this._deviceIdField = value;
                    this.RaisePropertyChanged("_deviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _objectId {
            get {
                return this._objectIdField;
            }
            set {
                if ((this._objectIdField.Equals(value) != true)) {
                    this._objectIdField = value;
                    this.RaisePropertyChanged("_objectId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Floor", Namespace="http://schemas.datacontract.org/2004/07/NuvoControl.Common.Configuration")]
    [System.SerializableAttribute()]
    public partial class Floor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _floorPlanPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _floorPlanTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NuvoControl.Server.WebServer.ConfigurationServiceReference.Address _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NuvoControl.Server.WebServer.ConfigurationServiceReference.Zone[] _zonesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _floorPlanPath {
            get {
                return this._floorPlanPathField;
            }
            set {
                if ((object.ReferenceEquals(this._floorPlanPathField, value) != true)) {
                    this._floorPlanPathField = value;
                    this.RaisePropertyChanged("_floorPlanPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _floorPlanType {
            get {
                return this._floorPlanTypeField;
            }
            set {
                if ((object.ReferenceEquals(this._floorPlanTypeField, value) != true)) {
                    this._floorPlanTypeField = value;
                    this.RaisePropertyChanged("_floorPlanType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Address _id {
            get {
                return this._idField;
            }
            set {
                if ((object.ReferenceEquals(this._idField, value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Zone[] _zones {
            get {
                return this._zonesField;
            }
            set {
                if ((object.ReferenceEquals(this._zonesField, value) != true)) {
                    this._zonesField = value;
                    this.RaisePropertyChanged("_zones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zone", Namespace="http://schemas.datacontract.org/2004/07/NuvoControl.Common.Configuration")]
    [System.SerializableAttribute()]
    public partial class Zone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NuvoControl.Server.WebServer.ConfigurationServiceReference.Point[] _floorPlanCoordinatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NuvoControl.Server.WebServer.ConfigurationServiceReference.Address _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _picturePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _pictureTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NuvoControl.Server.WebServer.ConfigurationServiceReference.Point _zoneControlCoordinateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Point[] _floorPlanCoordinates {
            get {
                return this._floorPlanCoordinatesField;
            }
            set {
                if ((object.ReferenceEquals(this._floorPlanCoordinatesField, value) != true)) {
                    this._floorPlanCoordinatesField = value;
                    this.RaisePropertyChanged("_floorPlanCoordinates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Address _id {
            get {
                return this._idField;
            }
            set {
                if ((object.ReferenceEquals(this._idField, value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _picturePath {
            get {
                return this._picturePathField;
            }
            set {
                if ((object.ReferenceEquals(this._picturePathField, value) != true)) {
                    this._picturePathField = value;
                    this.RaisePropertyChanged("_picturePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _pictureType {
            get {
                return this._pictureTypeField;
            }
            set {
                if ((object.ReferenceEquals(this._pictureTypeField, value) != true)) {
                    this._pictureTypeField = value;
                    this.RaisePropertyChanged("_pictureType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Point _zoneControlCoordinate {
            get {
                return this._zoneControlCoordinateField;
            }
            set {
                if ((this._zoneControlCoordinateField.Equals(value) != true)) {
                    this._zoneControlCoordinateField = value;
                    this.RaisePropertyChanged("_zoneControlCoordinate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Point", Namespace="http://schemas.datacontract.org/2004/07/System.Windows")]
    [System.SerializableAttribute()]
    public partial struct Point : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double _xField;
        
        private double _yField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double _x {
            get {
                return this._xField;
            }
            set {
                if ((this._xField.Equals(value) != true)) {
                    this._xField = value;
                    this.RaisePropertyChanged("_x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double _y {
            get {
                return this._yField;
            }
            set {
                if ((this._yField.Equals(value) != true)) {
                    this._yField = value;
                    this.RaisePropertyChanged("_y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NuvoImage", Namespace="http://schemas.datacontract.org/2004/07/NuvoControl.Common.Configuration")]
    [System.SerializableAttribute()]
    public partial class NuvoImage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _pathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Drawing.Bitmap _pictureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _path {
            get {
                return this._pathField;
            }
            set {
                if ((object.ReferenceEquals(this._pathField, value) != true)) {
                    this._pathField = value;
                    this.RaisePropertyChanged("_path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Drawing.Bitmap _picture {
            get {
                return this._pictureField;
            }
            set {
                if ((object.ReferenceEquals(this._pictureField, value) != true)) {
                    this._pictureField = value;
                    this.RaisePropertyChanged("_picture");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Function", Namespace="http://schemas.datacontract.org/2004/07/NuvoControl.Common.Configuration")]
    [System.SerializableAttribute()]
    public partial class Function : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NuvoControl.Server.WebServer.ConfigurationServiceReference.Address _zoneIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Address _zoneId {
            get {
                return this._zoneIdField;
            }
            set {
                if ((object.ReferenceEquals(this._zoneIdField, value) != true)) {
                    this._zoneIdField = value;
                    this.RaisePropertyChanged("_zoneId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigurationServiceReference.IConfigure")]
    public interface IConfigure {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigure/RenewLease", ReplyAction="http://tempuri.org/IConfigure/RenewLeaseResponse")]
        void RenewLease();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigure/GetGraphicConfiguration", ReplyAction="http://tempuri.org/IConfigure/GetGraphicConfigurationResponse")]
        NuvoControl.Server.WebServer.ConfigurationServiceReference.Graphic GetGraphicConfiguration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigure/GetImage", ReplyAction="http://tempuri.org/IConfigure/GetImageResponse")]
        NuvoControl.Server.WebServer.ConfigurationServiceReference.NuvoImage GetImage(string picturePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigure/GetZoneKonfiguration", ReplyAction="http://tempuri.org/IConfigure/GetZoneKonfigurationResponse")]
        NuvoControl.Server.WebServer.ConfigurationServiceReference.Zone GetZoneKonfiguration(NuvoControl.Server.WebServer.ConfigurationServiceReference.Address zoneId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigure/GetFunction", ReplyAction="http://tempuri.org/IConfigure/GetFunctionResponse")]
        NuvoControl.Server.WebServer.ConfigurationServiceReference.Function GetFunction(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigure/GetFunctions", ReplyAction="http://tempuri.org/IConfigure/GetFunctionsResponse")]
        NuvoControl.Server.WebServer.ConfigurationServiceReference.Function[] GetFunctions(NuvoControl.Server.WebServer.ConfigurationServiceReference.Address zoneId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigure/AddFunction", ReplyAction="http://tempuri.org/IConfigure/AddFunctionResponse")]
        bool AddFunction(NuvoControl.Server.WebServer.ConfigurationServiceReference.Function newFunction);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfigureChannel : NuvoControl.Server.WebServer.ConfigurationServiceReference.IConfigure, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigureClient : System.ServiceModel.ClientBase<NuvoControl.Server.WebServer.ConfigurationServiceReference.IConfigure>, NuvoControl.Server.WebServer.ConfigurationServiceReference.IConfigure {
        
        public ConfigureClient() {
        }
        
        public ConfigureClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigureClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigureClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RenewLease() {
            base.Channel.RenewLease();
        }
        
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Graphic GetGraphicConfiguration() {
            return base.Channel.GetGraphicConfiguration();
        }
        
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.NuvoImage GetImage(string picturePath) {
            return base.Channel.GetImage(picturePath);
        }
        
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Zone GetZoneKonfiguration(NuvoControl.Server.WebServer.ConfigurationServiceReference.Address zoneId) {
            return base.Channel.GetZoneKonfiguration(zoneId);
        }
        
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Function GetFunction(System.Guid id) {
            return base.Channel.GetFunction(id);
        }
        
        public NuvoControl.Server.WebServer.ConfigurationServiceReference.Function[] GetFunctions(NuvoControl.Server.WebServer.ConfigurationServiceReference.Address zoneId) {
            return base.Channel.GetFunctions(zoneId);
        }
        
        public bool AddFunction(NuvoControl.Server.WebServer.ConfigurationServiceReference.Function newFunction) {
            return base.Channel.AddFunction(newFunction);
        }
    }
}
